### ISSUE TITLE
Request: getting started instructions

### ISSUE THREAD

**Issue by jamesbraza** [KirillRepinArt/ChatGPT-UI#1]
I use [text-generation-webui](https://github.com/oobabooga/text-generation-webui) and like this front end!

Can you add "getting started" instructions for this?  I would like to migrate to use this.

**Comment by KirillRepinArt** [comment]
> I use [text-generation-webui](https://github.com/oobabooga/text-generation-webui) and like this front end!
> 
> Can you add "getting started" instructions for this? I would like to migrate to use this.

The issue here is with different versions of TextGen-UI. 

I've made Chat-GPT style for the older version, I think the latest update for it was from July 2023. 

At some point after that, Text-Gen changed it's base UI layout. So now, some of the containers I've targeted with CSS are no longer there, and Chat-GPT style doesn't work properly unless you have an older UI version with its older layout.

I've created this repo in hope, that people who are more knowledgeable than myself, would be able to adapt my style to the newer versions of UI, so everybody would be able to use it, but no luck so far.

I think, I'll try to do it myself, but I'm afraid I can't give you a timeline for that.

**Comment by jamesbraza** [comment]
Ah okay, I gotchu. Yeah for many places, July 2023 is not that old, but these LLM frameworks change so fast.

It's up to you if you want to revive this or not.  If you do, circle back and I will adopt 👍

**Comment by KirillRepinArt** [comment]
> Ah okay, I gotchu. Yeah for many places, July 2023 is not that old, but these LLM frameworks change so fast.
> 
> It's up to you if you want to revive this or not. If you do, circle back and I will adopt 👍

You can try the new version of the style now. 

I've updated it to work with the latest (I think) version of the TextGen. 
I've also added an instruction, it's pretty straightforward.

Let me know if it works for you!

**Comment by jamesbraza** [comment]
Hello @KirillRepinArt I got it working with https://github.com/oobabooga/text-generation-webui/tree/3d1c0f173d00bd968cd6d2b1857ff23a58e695c3!  I made https://github.com/KirillRepinArt/ChatGPT-UI/pull/2 to improve the getting started docs based on my learnings 👍
